---
title: "002_1_AnalysisHighLowTime.RMD"
author: "Callin Switzer"
date: "August 6, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

windows = ifelse(grepl(pattern = "wind", ignore.case = TRUE, 
                       x = Sys.info()[1]), TRUE, FALSE)

{if(windows){
  rd = "D:/Dropbox/SonicationBehavior"
}
else{
  rd = "/Users/cswitzer/Dropbox/SonicationBehavior"
}}


knitr::opts_knit$set(root.dir =rd )
```

```{r, warning = FALSE}
#install packages
ipak <- function(pkg){
     new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
     if(length(new.pkg)) install.packages(new.pkg, dependencies = TRUE)
     sapply(pkg, require, character.only = TRUE)
}

packages <- c("plyr", "tidyverse", "reshape2", 'lme4', 'sjPlot', 
              "multcomp", "effects", "lubridate")
ipak(packages)

# set ggplot theme
theme_set(theme_classic() + theme(axis.text=element_text(colour="black")))

# define data and figure directories
{if(windows){
  # windows
  dataDir <- "D:/Dropbox/SonicationBehavior/SonBehData"
  figDir <- "D:/Dropbox/SonicationBehavior/SonBehFigs"
  }
else{
  # mac
  dataDir <- "/Users/cswitzer/Dropbox/SonicationBehavior/SonBehData"
  figDir <- "/Users/cswitzer/Dropbox/SonicationBehavior/SonBehFigs"
}}


# check if the directory exists
file.info(dataDir)$isdir
print(dataDir)

print(paste("last run ", Sys.time()))
print(R.version)

```

### Read in data and add columns

```{r}
sl <- read_csv(file.path(dataDir, '01_CombinedTrials_cleaned.csv'))
colnames(sl)

options(digits.secs=6)
sl <- sl %>% 
  mutate(dateTime_fmt =  as.POSIXct(as.character(datetime_str), 
                                    format = "%Y-%m-%d  %H:%M:%OS"), 
         beeColHive = as.character(interaction(beeCol, hive))) %>%
  arrange(beeColHive,trialNum, dateTime_fmt) %>% 
  group_by(beeColHive, trialNum) %>%
  mutate(timeDiff = as.numeric(difftime(dateTime_fmt, lag(dateTime_fmt), units = "sec"))) 

# add NA for time diff whenever a new trial starts
for(ii in 1:(nrow(sl) - 1)){
  if(sl$BeeNumCol[ii + 1] != sl$BeeNumCol[ii]){
    sl$timeDiff[ii + 1] <- NA
  }
}

sl <- sl %>%
  # add cumulative time for each bee
  transform(OverallTime = ave(timeDiff, interaction(beeColHive), FUN=function(x) cumsum(coalesce(x, 0)) + x*0)) %>%
  # calculate continuous buzz number
  mutate(continuousCount = ave(beeColHive==beeColHive,beeColHive, FUN=cumsum), 
        rewardTF = grepl("t", tolower(rewTF))) %>%
  # separate each trial by 1 minute
  mutate(OverallTime_sep = OverallTime + 60*trialNum) # add 1 min breaks between trials



# View(sl)

```




```{r}
# plot buzz times vs rewards


sl %>%
  filter(trt != "full") %>%
ggplot( aes(x = continuousCount, y = rewardTF*1)) + 
  geom_point(alpha = 0.2, pch = 21, fill = 'black', stroke = 0,  position=position_jitter(width = 0, height = 0.1)) + 
  facet_wrap(~interaction(beeColHive, trt)) + 
  #stat_smooth(method = 'loess', aes(color = as.factor(trialNum)), se = FALSE, span = 5) + 
  scale_color_viridis_d()
ggsave(filename = file.path(figDir, "buzzesByNumber.svg"), width = 100, height = 10, limitsize = FALSE)




sl %>%
  filter(trt != "full") %>%
ggplot( aes(x = OverallTime, y = rewardTF*1)) + 
  geom_point(alpha = 0.2, pch = 21, fill = 'black', stroke = 0,  position=position_jitter(width = 0, height = 0.1)) +   
  facet_wrap(~interaction(beeColHive, trt)) + 
  stat_smooth(method = 'loess', aes(color = as.factor(trialNum)), se = FALSE, span = 5) + 
  scale_color_viridis_d()
ggsave(filename = file.path(figDir, "buzzesOverTime.svg"), width = 100, height = 10, limitsize = FALSE)


sl %>%
  filter(trt != "full") %>%
ggplot( aes(x = OverallTime, fill = rewardTF)) + 
  geom_histogram() + 
  facet_wrap(~interaction(beeColHive, trt)) +
  scale_fill_viridis_d()



newDF2 <- sl %>%
  filter(trt != "full")
ggplot(newDF2, aes(x=continuousCount,fill=rewardTF)) + 
  geom_histogram(data=subset(newDF2,rewardTF==TRUE), aes(y = ..count..),color = 'grey10', lwd = 0.1, binwidth = 100) +
  geom_histogram(data=subset(newDF2,rewardTF==FALSE),aes( y=..count..*(-1)), color = 'grey10', lwd = 0.1, binwidth = 100 ) + 
  scale_y_continuous(breaks=seq(-200,200,20),labels=abs(seq(-200,200,20))) + 
  facet_wrap(~interaction(beeColHive, trt), ncol = 6) +
  theme_classic() + 
  theme(legend.position = c(0.8,0.1) , 
        axis.text.x = element_text(angle = 90, size = 7), 
        legend.direction = "horizontal")+ 
  scale_fill_viridis_d(direction = 1, option = "cividis", name = "Rewarded", end = 0.9, begin = 0.3) + 
  geom_point(data = newDF2, inherit.aes = FALSE, aes(x = continuousCount,  y = -100, color = factor(trialNum)),
            lwd = 4, pch = 15)+ 
  scale_color_viridis_d(direction = 1, option = "plasma",  name = "Trial Num") + 
  xlab("Sonication Number") + 
  ylab("Frequency")

ggsave(filename = file.path(figDir, "buzzesOverBuzzCount_hist.svg"), width = 20, height = 10, limitsize = FALSE)





newDF2 <- sl %>%
  filter(trt != "full") 


timeCutoff <- newDF2 %>%
  subset(is.na(newDF2$timeDiff)) %>%
  rownames() %>%
  as.numeric()

ggplot(newDF2, aes(x=OverallTime,fill=rewardTF)) + 
  geom_vline( data = newDF2[timeCutoff - 1, ], aes(xintercept = OverallTime)) + 
  geom_vline( data = newDF2[timeCutoff +1, ], aes(xintercept = OverallTime)) + 
  geom_histogram(data=subset(newDF2,rewardTF==TRUE), aes(y = ..count..),color = 'grey10', lwd = 0.1, binwidth = 200) +
  geom_histogram(data=subset(newDF2,rewardTF==FALSE),aes( y=..count..*(-1)), color = 'grey10', lwd = 0.1, binwidth = 200 ) + 
  scale_y_continuous(breaks=seq(-200,200,20),labels=abs(seq(-200,200,20))) + 
  facet_wrap(trt ~ beeColHive, ncol = 6) +
  theme_classic() + 
  theme(legend.position = c(0.8,0.1) , 
        axis.text.x = element_text(angle = 90, size = 7), 
        legend.direction = "horizontal")+ 
  scale_fill_viridis_d(direction = 1, option = "cividis", name = "Rewarded", end = 0.9, begin = 0.3) + 
  geom_point(data = newDF2, inherit.aes = FALSE, aes(x = OverallTime,  y = -200, color = factor(trialNum)),
            lwd = 4, pch = 15)+ 
  scale_color_viridis_d(direction = 1, option = "plasma",  name = "Trial Num") + 
  xlab("Time (s)") + 
  ylab("Frequency") 

ggsave(filename = file.path(figDir, "buzzesOverTime_hist.svg"), width = 20, height = 10, limitsize = FALSE)




# newDF2 <- sl %>%
#   filter(beeColHive %in% unique(sl$beeColHive[sl$beeColHive %in% sl$beeColHive[sl$trt != "full"]]))
newDF2 <- sl %>%
  filter(trt != "full") 
newDF2$rewardString = mapvalues(newDF2$rewardTF, from  = c(TRUE, FALSE), to = c("Rewarded", "Unrewarded"))

textSize = 3

paste(with(newDF2, as.character(unique(interaction(beeColHive, trt)))), collapse = "\', \'")
newDF2$facet_labels = with(newDF2,gsub(x = paste0(interaction(trt,  formatC(as.numeric(as.factor(beeColHive)), width = 2, flag = 0))), pattern = "\\.",replacement = " freq reward, bee "))


# with(newDF2, formatC(as.numeric(as.factor(beeColHive)), width = 2, flag = 0))

ann_text <- data.frame(OverallTime_sep = 5000, lab = "Reward", facet_labels = factor(c("high freq reward, bee 03", "low freq reward, bee 01"), levels = levels(as.factor(newDF2$facet_labels))))

ggplot(newDF2, aes(x=OverallTime_sep/60,fill=rewardString, group = as.factor(trialNum))) + 
  geom_hline(aes(yintercept =0), lwd = 0.01, alpha = 0.2) + 
  geom_line(data = newDF2, inherit.aes = FALSE, aes(x = OverallTime_sep/60,  y = -50, color = factor(trialNum)),
            lwd = 400, show.legend = FALSE, alpha = 0.1)+ 
  geom_histogram(data=subset(newDF2,rewardTF==TRUE), aes(y = ..count..),color = NA, size = 0.0, binwidth = 50/60) +
  geom_histogram(data=subset(newDF2,rewardTF==FALSE),aes( y=..count..*(-1)), color = NA, size = 0.0, binwidth = 50/60 ) + 
  scale_y_continuous(breaks=seq(-60,60,10),labels=abs(seq(-60,60,10))) + 
  facet_wrap(~facet_labels, ncol = 6) +
  theme_classic() + 
  theme(legend.position = c(0.6,0.1) , 
        axis.text.x = element_text(angle = 0, size = 8), 
        legend.direction = "vertical", 
        legend.title = element_blank(), 
        legend.box.background = element_rect(colour = "black"))+ 
  scale_fill_viridis_d(direction = -1, option = "cividis", name = "", end = 0.9, begin = 0.3) + 
  scale_color_viridis_d(direction = 1, option = "plasma",  name = "Trial Num") + 
  xlab("Time (min)") + 
  ylab("Number of visits")  + 
  geom_text(inherit.aes = FALSE, data = ann_text, aes(x = OverallTime_sep/60, label = "Rewarded", y = 5), size = textSize) + 
  geom_text(inherit.aes = FALSE, data = ann_text, aes(x = OverallTime_sep/60, label = "Unrewarded", y = -5), size = textSize)

ggsave(filename = file.path(figDir, "buzzesOverTime_hist_TimeSep.svg"), width = 11.5, height = 8, limitsize = FALSE)
ggsave(filename = file.path(figDir, "buzzesOverTime_hist_TimeSep.png"), dpi = 200, width = 11.5, height = 8, limitsize = FALSE)

ggsave(filename = file.path(figDir, "buzzesOverTime_hist_TimeSep_small.png"), dpi = 200, width = 9.6, height = 7, limitsize = FALSE)


ggplot(newDF2, aes(x=OverallTime,fill=rewardTF, group = as.factor(trialNum))) + 
  geom_density(data=subset(newDF2,rewardTF==TRUE), aes(y = ..count..),color = 'grey10', lwd = 0.1, n = 256) +
  geom_density(data=subset(newDF2,rewardTF==FALSE),aes( y=..count..*(-1)), color = 'grey10', lwd = 0.1, n=256 , alpha = 0.2) + 
  scale_y_continuous(breaks=seq(-2,2,0.5),labels=abs(seq(-2,2,0.5))) + 
  facet_wrap(~interaction(beeColHive, trt), ncol = 6) +
  theme_classic() + 
  theme(legend.position = c(0.8,0.1) , 
        axis.text.x = element_text(angle = 90, size = 7), 
        legend.direction = "horizontal")+ 
  scale_fill_viridis_d(direction = 1, option = "cividis", name = "Rewarded", end = 0.9, begin = 0.3) + 
  geom_point(data = newDF2, inherit.aes = FALSE, aes(x = OverallTime,  y = -0.9, color = factor(trialNum, levels = c(2,6,10,3,7,11,4,8,12,5,9))),
            lwd = 4, pch = 15)+ 
  scale_color_viridis_d(direction = 1, option = "plasma",  name = "Trial Num") + 
  xlab("Time (s)") + 
  ylab("Frequency")

ggsave(filename = file.path(figDir, "buzzesOverTime_Density.svg"), width = 20, height = 10, limitsize = FALSE)



```